# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'lost100' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'QBImagePickerController'
	pod 'RSKImageCropper'
  # Pods for lost100
end
